### ISSUE TITLE
下载了Demo无法运行

### ISSUE THREAD

**Issue by Biswangluo** [xiaoxiangyeyuHeaven/HeavenlyModule#5]
![qq 20170614100708](https://user-images.githubusercontent.com/2362450/27112371-47d514e2-50e9-11e7-84aa-b6c2fad91fef.png)

**Comment by Biswangluo** [comment]
自己修好了 提上去了 rxJava 1 2 的兼容性问题

**Comment by yt511652502** [comment]
非常感谢

**Comment by xiaoxiangyeyu123** [comment]
对不起  昨天有点着急 忘记了 修改Subscriber这个类了  导致了demo报错 十分抱歉
